import { StyleSheet } from 'react-native';

export const supportStyles = StyleSheet.create({
  page: { flex: 1 },
  header: { height: 58, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth },
  back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '700' },
  content: { padding: 18, paddingBottom: 120, gap: 14, width: '100%', maxWidth: 680, alignSelf: 'center' },
  title: { fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -0.8 },
  subtitle: { fontSize: 15, lineHeight: 21, marginTop: -6 },
  notice: { minHeight: 66, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12 },
  noticeText: { flex: 1, fontSize: 15, lineHeight: 20, fontWeight: '600' },
  signInCard: { minHeight: 92, borderRadius: 16, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 13 },
  signInIcon: { width: 52, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  signInCopy: { flex: 1 },
  signInTitle: { color: '#FFFFFF', fontSize: 17, lineHeight: 22, fontWeight: '700' },
  signInBody: { color: 'rgba(255,255,255,0.72)', fontSize: 14, lineHeight: 19, marginTop: 2 },
  topicGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  topic: { minHeight: 44, borderRadius: 11, borderWidth: 1, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center' },
  topicText: { fontSize: 14, fontWeight: '600' },
  input: { minHeight: 138, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, padding: 14, fontSize: 15, lineHeight: 21, textAlignVertical: 'top' },
  councilContext: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingHorizontal: 2 },
  councilContextText: { flex: 1, fontSize: 13, lineHeight: 18 },
  button: { minHeight: 50, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  buttonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  feedback: { fontSize: 14, lineHeight: 19, fontWeight: '600' },
  conversationSection: { gap: 12, marginTop: 14 },
  sectionHeading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  sectionKicker: { fontSize: 12, lineHeight: 16, fontWeight: '700', letterSpacing: 1.2 },
  sectionTitle: { fontSize: 24, lineHeight: 29, fontWeight: '700', letterSpacing: -0.5, marginTop: 2 },
  count: { fontSize: 14, fontWeight: '600' },
  threadTabs: { gap: 9, paddingRight: 4 },
  threadTab: { width: 180, minHeight: 68, borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, paddingVertical: 10, justifyContent: 'center' },
  threadTabTitle: { fontSize: 14, lineHeight: 18, fontWeight: '700' },
  threadTabMeta: { fontSize: 12, lineHeight: 16, marginTop: 3 },
  conversation: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, overflow: 'hidden' },
  conversationHead: { padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  conversationHeadCopy: { flex: 1 },
  conversationTitle: { fontSize: 17, lineHeight: 22, fontWeight: '700' },
  conversationMeta: { fontSize: 13, lineHeight: 18, marginTop: 2 },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  messageStack: { padding: 13, gap: 9 },
  messageRow: { flexDirection: 'row', paddingRight: 34 },
  messageRowResident: { justifyContent: 'flex-end', paddingRight: 0, paddingLeft: 34 },
  messageBubble: { maxWidth: '100%', borderRadius: 15, paddingHorizontal: 13, paddingVertical: 10 },
  messageText: { fontSize: 15, lineHeight: 21 },
  messageTime: { fontSize: 11, lineHeight: 15, marginTop: 5 },
  replyBox: { minHeight: 65, borderTopWidth: StyleSheet.hairlineWidth, padding: 9, flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  replyInput: { flex: 1, minHeight: 44, maxHeight: 130, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, fontSize: 15, lineHeight: 20 },
  replyButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  closedText: { padding: 14, fontSize: 13, lineHeight: 18 },
  satisfaction: { padding: 15, borderTopWidth: StyleSheet.hairlineWidth, alignItems: 'center' },
  satisfactionTitle: { fontSize: 16, lineHeight: 21, fontWeight: '700' },
  satisfactionBody: { marginTop: 3, fontSize: 13, lineHeight: 18, textAlign: 'center' },
  satisfactionScores: { flexDirection: 'row', gap: 8, marginTop: 12 },
  scoreButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  scoreText: { fontSize: 15, fontWeight: '700' },
  satisfactionResult: { minHeight: 62, padding: 14, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  pressed: { opacity: 0.68 },
  disabled: { opacity: 0.48 },
});
