import { StyleSheet } from 'react-native';

import { appFonts } from '@/lib/design-system';
import { AppTheme } from '@/lib/theme';

export function createPlacesStyles(theme: AppTheme) {
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: theme.background },
    safe: { backgroundColor: theme.surface, paddingTop: 14, paddingHorizontal: 20, paddingBottom: 22 },
    kicker: { color: theme.accent, fontFamily: appFonts.text, fontSize: 12, letterSpacing: 0.6, fontWeight: '700' },
    title: { color: theme.text, fontFamily: appFonts.display, fontSize: 32, lineHeight: 38, fontWeight: '700', letterSpacing: -1.05, marginTop: 3 },
    subtitle: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 18, marginTop: 7, maxWidth: 310, fontWeight: '500' },
    content: { padding: 18, paddingBottom: 120, gap: 17 },
    locationCard: { minHeight: 79, borderRadius: 16, paddingHorizontal: 15, backgroundColor: theme.hero, flexDirection: 'row', alignItems: 'center', gap: 12 },
    locationIcon: { height: 42, width: 42, borderRadius: 15, backgroundColor: theme.accentFill, alignItems: 'center', justifyContent: 'center' },
    locationCopy: { flex: 1 },
    locationTitle: { color: theme.heroText, fontSize: 14, fontWeight: '700' },
    locationBody: { color: theme.heroSecondary, fontSize: 12.5, lineHeight: 17, marginTop: 3, fontWeight: '600' },
    sectionHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', paddingHorizontal: 2 },
    sectionTitle: { color: theme.text, fontSize: 14, fontWeight: '800' },
    count: { color: theme.secondaryText, fontSize: 12, fontWeight: '700' },
    placeList: { backgroundColor: theme.surface, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, overflow: 'hidden' },
    emptyPlaces: { minHeight: 84, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 12 },
    emptyPlacesCopy: { flex: 1 },
    emptyPlacesTitle: { color: theme.text, fontSize: 13.5, fontWeight: '700' },
    emptyPlacesBody: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, marginTop: 4 },
    placeCard: { minHeight: 91, paddingRight: 14, flexDirection: 'row', alignItems: 'center' },
    placeSelect: { flex: 1, minHeight: 91, paddingLeft: 14, paddingVertical: 13, flexDirection: 'row', alignItems: 'center', gap: 12 },
    placeBorder: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    placeActive: { backgroundColor: theme.accentSoft },
    homeIcon: { height: 42, width: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.accentSoft },
    homeIconActive: { backgroundColor: theme.accentFill },
    placeCopy: { flex: 1 },
    visibleRemove: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
    labelRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    placeLabel: { color: theme.text, fontSize: 14.5, fontWeight: '700', letterSpacing: -0.15 },
    activePill: { backgroundColor: theme.accentSoft, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6 },
    activePillText: { color: theme.accent, fontSize: 12, fontWeight: '700' },
    placeAddress: { color: theme.secondaryText, fontSize: 12.5, marginTop: 4, fontWeight: '600' },
    council: { color: theme.secondaryText, fontSize: 12, marginTop: 3 },
    removeAction: { width: 92, alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: theme.danger },
    removeActionPressed: { backgroundColor: theme.danger, opacity: 0.86 },
    removeActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
    swipeHint: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: -8, paddingHorizontal: 4 },
    swipeHintText: { color: theme.secondaryText, fontSize: 12, fontWeight: '600' },
    syncCard: { borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: theme.accentSoft },
    syncCopy: { flex: 1 },
    syncTitle: { color: theme.text, fontSize: 13.5, fontWeight: '700' },
    syncBody: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, marginTop: 3, fontWeight: '500' },
    sharePlace: { minHeight: 62, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, backgroundColor: theme.surface, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11 },
    sharePlaceTitle: { color: theme.text, fontSize: 14, fontWeight: '700' },
    sharePlaceBody: { color: theme.secondaryText, fontSize: 12, lineHeight: 17, marginTop: 2 },
    addPanel: { backgroundColor: theme.surface, padding: 17, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, gap: 12 },
    addHeader: { flexDirection: 'row', justifyContent: 'space-between' },
    addHeaderCopy: { flex: 1 },
    addTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 20, lineHeight: 25, fontWeight: '700', letterSpacing: -0.4 },
    addDescription: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, marginTop: 4 },
    fieldLabel: { color: theme.secondaryText, fontSize: 12, letterSpacing: 0.5, fontWeight: '700', marginTop: 5 },
    input: { height: 47, borderRadius: 12, borderWidth: 1, borderColor: theme.separator, color: theme.text, paddingHorizontal: 13, backgroundColor: theme.elevated, fontSize: 15, fontWeight: '700' },
    addButton: { height: 46, borderRadius: 13, backgroundColor: theme.accentFill, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginTop: 2 },
    addButtonText: { color: '#FFFFFF', fontSize: 13.5, fontWeight: '700' },
    newPlace: { minHeight: 79, borderRadius: 14, borderWidth: 1.5, borderColor: theme.separator, borderStyle: 'dashed', alignItems: 'center', flexDirection: 'row', gap: 12, paddingHorizontal: 15 },
    plus: { height: 37, width: 37, borderRadius: 13, backgroundColor: theme.accentSoft, alignItems: 'center', justifyContent: 'center' },
    newPlaceTitle: { color: theme.text, fontSize: 13.5, fontWeight: '700' },
    newPlaceCopy: { color: theme.secondaryText, fontSize: 12.5, marginTop: 3 },
    note: { paddingHorizontal: 5, flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
    noteText: { color: theme.secondaryText, fontSize: 12, lineHeight: 17, flex: 1 },
    addressModal: { flex: 1, backgroundColor: theme.background },
    modalHeader: { backgroundColor: theme.surface, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 20, flexDirection: 'row', gap: 12, borderBottomWidth: 1, borderBottomColor: theme.separator },
    modalHeaderCopy: { flex: 1 },
    modalKicker: { color: theme.accent, fontFamily: appFonts.text, fontSize: 12, letterSpacing: 0.6, fontWeight: '700' },
    modalTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -0.8, marginTop: 3 },
    modalBody: { color: theme.secondaryText, fontSize: 13, lineHeight: 18, marginTop: 7, maxWidth: 320 },
    modalClose: { height: 36, width: 36, borderRadius: 18, backgroundColor: theme.elevated, alignItems: 'center', justifyContent: 'center' },
    addressList: { padding: 16, paddingBottom: 30 },
    addressOption: { minHeight: 70, backgroundColor: theme.surface, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, marginBottom: 9, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 11 },
    addressOptionIcon: { height: 39, width: 39, borderRadius: 13, backgroundColor: theme.accentSoft, alignItems: 'center', justifyContent: 'center' },
    addressOptionCopy: { flex: 1 },
    addressOptionTitle: { color: theme.text, fontSize: 13, lineHeight: 17, fontWeight: '800' },
    addressOptionPostcode: { color: theme.secondaryText, fontSize: 12, marginTop: 3, fontWeight: '600' },
    pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
    disabled: { opacity: 0.6 },
  });
}

export type PlacesStyles = ReturnType<typeof createPlacesStyles>;
