import { StyleSheet } from 'react-native';

import { appFonts, appLayout, platformShadow } from '@/lib/design-system';
import { type AppTheme } from '@/lib/theme';

export function createScheduleStyles(theme: AppTheme, roomy: boolean) {
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: theme.background },
    headerButton: { width: 44, height: 44, borderRadius: 14, backgroundColor: theme.accentSoft, alignItems: 'center', justifyContent: 'center' },
    agendaContent: { paddingBottom: 112 },
    listHeader: { padding: appLayout.residentCompactGutter, gap: 14 },
    listFooter: { padding: appLayout.residentCompactGutter, paddingTop: 24, gap: 16 },
    emptyContent: { padding: roomy ? appLayout.residentWideGutter : appLayout.residentCompactGutter, paddingBottom: 80, maxWidth: 720, width: '100%', alignSelf: 'center' },
    statusStack: { gap: 10 },
    statusLine: { borderRadius: 14, padding: 13, backgroundColor: theme.accentSoft, flexDirection: 'row', gap: 10, alignItems: 'center' },
    statusLineWarning: { backgroundColor: `${theme.warning}14` },
    statusText: { flex: 1, color: theme.secondaryText, fontSize: 12.5, lineHeight: 18, fontWeight: '600' },
    viewPicker: { minHeight: 46, padding: 3, borderRadius: 14, backgroundColor: theme.groupedBackground, flexDirection: 'row', gap: 3 },
    viewOption: { flex: 1, minHeight: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
    viewOptionSelected: { backgroundColor: theme.surface, ...platformShadow('0 2px 5px rgba(0,0,0,0.08)', { shadowColor: '#000000', shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } }) },
    viewOptionText: { color: theme.secondaryText, fontSize: 13, fontWeight: '700' },
    viewOptionTextSelected: { color: theme.text },
    compactSectionHeader: { minHeight: 72, paddingHorizontal: appLayout.residentCompactGutter, paddingTop: 15, paddingBottom: 9, backgroundColor: theme.background, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    dateLabel: { color: theme.secondaryText, fontFamily: appFonts.text, fontSize: 12, fontWeight: '700' },
    dateLong: { color: theme.text, fontFamily: appFonts.display, fontSize: 20, lineHeight: 25, fontWeight: '700', letterSpacing: -0.45, marginTop: 2 },
    dayStamp: { height: 44, width: 44, borderRadius: 14, backgroundColor: theme.groupedBackground, alignItems: 'center', justifyContent: 'center' },
    dayStampToday: { backgroundColor: theme.accentFill },
    dayStampText: { color: theme.text, fontFamily: appFonts.rounded, fontSize: 17, fontWeight: '700', fontVariant: ['tabular-nums'] },
    dayStampTextToday: { color: '#FFFFFF' },
    collectionsCard: { marginHorizontal: roomy ? 0 : appLayout.residentCompactGutter, backgroundColor: theme.surface, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, overflow: 'hidden' },
    collectionRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 11, backgroundColor: theme.surface },
    collectionBorder: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    iconCircle: { height: 42, width: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
    rowCopy: { flex: 1, minWidth: 0 },
    rowTitle: { color: theme.text, fontSize: 15, lineHeight: 20, fontWeight: '800' },
    placeLabel: { color: theme.accent, fontSize: 11.5, lineHeight: 16, marginTop: 2, fontWeight: '700' },
    rowInfo: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, marginTop: 3, fontWeight: '600' },
    statusDot: { height: 8, width: 8, borderRadius: 4 },
    rowCalendar: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
    primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: theme.accentFill, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
    primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
    disabled: { opacity: 0.5 },
    calendarOptions: { gap: 9 },
    calendarTitle: { color: theme.secondaryText, fontSize: 13, fontWeight: '700' },
    calendarTypes: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    calendarType: { minHeight: 44, borderRadius: 12, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 7, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, backgroundColor: theme.surface },
    calendarTypeSelected: { borderColor: theme.accent, backgroundColor: theme.accentSoft },
    calendarTypeText: { color: theme.secondaryText, fontSize: 12.5, fontWeight: '600' },
    calendarTypeTextSelected: { color: theme.accent, fontWeight: '700' },
    cycleFootnote: { color: theme.tertiaryText, fontSize: 12, lineHeight: 17 },
    actionsCard: { backgroundColor: theme.surface, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, overflow: 'hidden' },
    actionRow: { minHeight: 56, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    actionRowLast: { borderBottomWidth: 0 },
    actionText: { flex: 1, minWidth: 0, color: theme.text, fontSize: 14, lineHeight: 19, fontWeight: '700' },
    pressed: { opacity: 0.7, transform: [{ scale: 0.988 }] },
    desktopWorkspace: { flex: 1, minWidth: 0, flexDirection: 'row' },
    calendarPane: { flex: 3, minWidth: 0, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: theme.separator },
    detailPane: { flex: 2, minWidth: 260, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: theme.separator },
    contextPane: { flex: 2, minWidth: 260 },
    calendarColumn: { padding: appLayout.residentMediumGutter, gap: 16 }, detailColumn: { padding: appLayout.residentMediumGutter, gap: 16 }, contextColumn: { padding: appLayout.residentMediumGutter, gap: 14 },
    monthCard: { borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, backgroundColor: theme.surface, padding: 18 },
    monthHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12, marginBottom: 16 },
    sectionKicker: { color: theme.secondaryText, fontSize: 12, lineHeight: 16, fontWeight: '700', letterSpacing: 0.5 },
    monthTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 25, lineHeight: 31, fontWeight: '700', marginTop: 2 },
    monthHint: { color: theme.tertiaryText, fontSize: 12, fontWeight: '600' },
    weekHeader: { flexDirection: 'row' }, weekDay: { width: `${100 / 7}%`, color: theme.secondaryText, fontSize: 11, lineHeight: 18, fontWeight: '700', textAlign: 'center' }, monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5 },
    dayCell: { width: `${100 / 7}%`, aspectRatio: 1.1, minHeight: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 4 }, dayCellOutside: { opacity: 0.4 }, dayCellSelected: { backgroundColor: theme.accentFill }, dayCellText: { color: theme.text, fontFamily: appFonts.rounded, fontSize: 14, fontWeight: '700' }, dayCellTextOutside: { color: theme.tertiaryText }, dayCellTextSelected: { color: '#FFFFFF' }, collectionMarker: { width: 5, height: 5, borderRadius: 3, backgroundColor: theme.accentFill }, collectionMarkerSelected: { backgroundColor: '#FFFFFF' },
    detailHeading: { gap: 2 }, detailTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 25, lineHeight: 31, fontWeight: '700' }, detailSubtitle: { color: theme.secondaryText, fontSize: 13, lineHeight: 18 }, contextTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 20, lineHeight: 25, fontWeight: '700' }, contextBody: { color: theme.secondaryText, fontSize: 13, lineHeight: 19 },
    refreshButton: { minHeight: 48, borderRadius: 13, backgroundColor: theme.accentSoft, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, refreshButtonText: { color: theme.accent, fontSize: 14, fontWeight: '700' },
    sheetPage: { flex: 1, backgroundColor: theme.background }, sheetHeader: { minHeight: 58, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.surface, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator }, sheetHeaderButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, sheetTitle: { color: theme.text, fontSize: 17, fontWeight: '700' }, sheetContent: { padding: 18, paddingBottom: 40, gap: 14 },
  });
}

export type ScheduleStyles = ReturnType<typeof createScheduleStyles>;
