import { StyleSheet } from 'react-native';

import { appFonts, appLayout, platformShadow } from '@/lib/design-system';
import { type AppTheme } from '@/lib/theme';
import { type AdaptiveLayoutMode } from '@/lib/use-adaptive-layout';

export function createTodayStyles(theme: AppTheme, mode: AdaptiveLayoutMode) {
  const roomy = mode !== 'compact';
  const wide = mode === 'wide';
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: theme.background },
    loadingPage: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, backgroundColor: theme.background },
    loadingText: { color: theme.secondaryText, fontFamily: appFonts.text, fontSize: 15, fontWeight: '600' },
    setupHero: { paddingHorizontal: 22, paddingBottom: 30, borderBottomLeftRadius: 34, borderBottomRightRadius: 34 },
    setupTitle: { color: theme.heroText, fontFamily: appFonts.display, fontSize: 36, lineHeight: 40, fontWeight: '700', letterSpacing: -1.15, marginTop: 7, maxWidth: 350 },
    setupSubtitle: { color: theme.heroSecondary, fontSize: 15, lineHeight: 21, fontWeight: '500', marginTop: 10, maxWidth: 340 },
    setupContent: { padding: 18, paddingBottom: 122, gap: 17 },
    setupCard: { backgroundColor: theme.surface, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, padding: 18, gap: 12 },
    fieldLabel: { color: theme.secondaryText, fontFamily: appFonts.text, fontSize: 12, letterSpacing: 0.35, fontWeight: '700' },
    input: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: theme.separator, color: theme.text, paddingHorizontal: 15, backgroundColor: theme.elevated, fontSize: 17, fontWeight: '700' },
    inputError: { borderColor: theme.danger },
    errorText: { color: theme.danger, fontSize: 13, lineHeight: 18, fontWeight: '600', marginTop: -5 },
    primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: theme.accentFill, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
    primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
    orRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    orLine: { height: StyleSheet.hairlineWidth, flex: 1, backgroundColor: theme.separator },
    orText: { color: theme.tertiaryText, fontSize: 12, fontWeight: '700' },
    locationButton: { minHeight: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, backgroundColor: theme.accentSoft },
    locationButtonText: { color: theme.accent, fontSize: 15, fontWeight: '700' },
    privacyLine: { flexDirection: 'row', gap: 9, alignItems: 'flex-start', paddingHorizontal: 5 },
    privacyText: { color: theme.secondaryText, fontSize: 13, lineHeight: 18, flex: 1 },
    hero: { paddingHorizontal: roomy ? appLayout.residentWideGutter : 20, paddingBottom: roomy ? 20 : 16, borderBottomLeftRadius: roomy ? 24 : 34, borderBottomRightRadius: roomy ? 24 : 34 },
    heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingTop: 4 },
    heroBrand: { flex: 1, paddingRight: 8 },
    heroActions: { flexDirection: 'row', gap: 8 },
    eyebrow: { color: '#64B5FF', fontFamily: appFonts.text, fontSize: 12, letterSpacing: 0.45, fontWeight: '700' },
    greeting: { color: theme.heroText, fontFamily: appFonts.display, fontSize: wide ? 38 : 32, lineHeight: wide ? 44 : 37, fontWeight: '700', letterSpacing: -0.95, marginTop: 2, maxWidth: wide ? 760 : undefined },
    addressButton: { height: 44, width: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.12)', justifyContent: 'center', alignItems: 'center' },
    heroBadge: { position: 'absolute', top: -2, right: -2, minWidth: 17, height: 17, paddingHorizontal: 4, borderRadius: 9, backgroundColor: theme.danger, alignItems: 'center', justifyContent: 'center' },
    heroBadgeText: { color: '#FFFFFF', fontSize: 9.5, lineHeight: 12, fontWeight: '800' },
    heroInfoRow: { marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 14 },
    heroInfoCopy: { flex: 1, minWidth: 0 },
    addressLine: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start', maxWidth: '100%' },
    addressText: { color: theme.heroSecondary, fontSize: 15, fontWeight: '600', flexShrink: 1 },
    answerSubtitle: { color: theme.heroSecondary, fontSize: 15, lineHeight: 20, fontWeight: '500', maxWidth: 300, marginTop: 2 },
    countdownOrb: { height: 72, width: 72, borderRadius: 36, borderWidth: 1, borderColor: 'rgba(100,181,255,0.52)', backgroundColor: 'rgba(2,13,23,0.22)', alignItems: 'center', justifyContent: 'center' },
    countdownNumber: { color: '#D7ECFF', fontFamily: appFonts.rounded, fontSize: 16, fontWeight: '800', fontVariant: ['tabular-nums'], letterSpacing: -0.4, textAlign: 'center' },
    countdownCaption: { color: '#8CC8FF', fontSize: 11, fontWeight: '800', letterSpacing: 0.6, marginTop: 1 },
    content: { paddingHorizontal: roomy ? appLayout.residentWideGutter : 18, paddingTop: roomy ? 24 : 20, paddingBottom: 120, gap: 20 },
    savedPlaces: { gap: 9 },
    savedPlacesLabel: { color: theme.secondaryText, fontSize: 12, lineHeight: 16, fontWeight: '700', letterSpacing: 0.5 },
    savedPlacesList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    savedPlace: { minHeight: 44, maxWidth: 220, borderRadius: 13, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: theme.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator },
    savedPlaceSelected: { backgroundColor: theme.accentFill, borderColor: theme.accent },
    savedPlaceText: { color: theme.text, fontSize: 13, lineHeight: 18, fontWeight: '700', flexShrink: 1 },
    savedPlaceTextSelected: { color: '#FFFFFF' },
    savedPlaceAdd: { minHeight: 44, borderRadius: 13, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: theme.accentSoft },
    savedPlaceAddText: { color: theme.accent, fontSize: 13, fontWeight: '700' },
    dashboard: { flexDirection: roomy ? 'row' : 'column', alignItems: 'flex-start', gap: roomy ? 24 : 20 },
    primaryColumn: { width: roomy ? (wide ? '62%' : '58%') : '100%', minWidth: 0, gap: 20 },
    contextColumn: { flex: roomy ? 1 : undefined, width: roomy ? undefined : '100%', minWidth: 0, gap: 16 },
    contextLinks: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, backgroundColor: theme.surface, overflow: 'hidden' },
    contextLink: { minHeight: 72, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    contextLinkCopy: { flex: 1, minWidth: 0 },
    contextLinkTitle: { color: theme.text, fontSize: 14, lineHeight: 19, fontWeight: '700' },
    contextLinkBody: { color: theme.secondaryText, fontSize: 12, lineHeight: 17, marginTop: 2 },
    setupRequiredCard: { minHeight: 92, backgroundColor: theme.surface, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, flexDirection: 'row', alignItems: 'center', padding: 15, gap: 13 },
    actionIcon: { height: 46, width: 46, borderRadius: 15, backgroundColor: theme.accentFill, alignItems: 'center', justifyContent: 'center' },
    actionCard: { backgroundColor: theme.surface, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, padding: 17, gap: 14, ...platformShadow('0 5px 12px rgba(0, 0, 0, 0.06)', { shadowColor: '#000000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }) },
    actionCardComplete: { backgroundColor: theme.accentSoft, borderColor: theme.separator },
    actionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    actionTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 22, lineHeight: 27, fontWeight: '700', letterSpacing: -0.5, marginTop: 3 },
    lifecycleDetail: { color: theme.secondaryText, fontSize: 13.5, lineHeight: 19, marginTop: -5 },
    actionBins: { gap: 10 },
    actionBinRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 11 },
    actionBinName: { color: theme.text, fontSize: 16, fontWeight: '700' },
    completeButton: { minHeight: 52, backgroundColor: theme.accentFill, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    completeButtonDone: { backgroundColor: theme.accentSoft },
    completeButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
    completeButtonTextDone: { color: theme.accent },
    outcomeActions: { gap: 9 },
    quickActions: { flexDirection: 'row', gap: 8 },
    quickAction: { flex: 1, minHeight: 48, borderRadius: 12, backgroundColor: theme.groupedBackground, alignItems: 'center', justifyContent: 'center', gap: 4 },
    quickActionText: { color: theme.accent, fontSize: 12, fontWeight: '700' },
    secondaryAction: { minHeight: 48, borderRadius: 13, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    secondaryActionText: { color: theme.accent, fontSize: 14, fontWeight: '700' },
    reminderStatus: { minHeight: 44, paddingHorizontal: 4, flexDirection: 'row', alignItems: 'center', gap: 8 },
    reminderStatusText: { flex: 1, color: theme.secondaryText, fontSize: 12.5, fontWeight: '600' },
    collectedButton: { minHeight: 50, backgroundColor: theme.accentFill, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    missedButton: { minHeight: 50, backgroundColor: theme.surface, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.danger, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    missedButtonText: { color: theme.danger, fontSize: 16, fontWeight: '700' },
    actionDisabled: { opacity: 0.45 },
    blockedReason: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 18, textAlign: 'center' },
    collectionCard: { overflow: 'hidden', minHeight: 94, backgroundColor: theme.surface, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, flexDirection: 'row', alignItems: 'center', paddingRight: 16, ...platformShadow('0 5px 12px rgba(0, 0, 0, 0.06)', { shadowColor: '#000000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }) },
    collectionColour: { width: 7, alignSelf: 'stretch', marginRight: 13 },
    collectionBinMark: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    cardCopy: { flex: 1, marginLeft: 12 },
    cardKicker: { color: theme.secondaryText, fontSize: 12, fontWeight: '700', letterSpacing: 0.35, marginBottom: 4 },
    cardTitle: { color: theme.text, fontSize: 16, fontWeight: '800', letterSpacing: -0.2 },
    cardBody: { color: theme.secondaryText, fontSize: 13, marginTop: 4, fontWeight: '500', lineHeight: 18 },
    emptySchedule: { minHeight: 88, borderRadius: 18, borderWidth: 1, borderStyle: 'dashed', borderColor: theme.separator, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 12 },
    emptyScheduleCopy: { flex: 1 },
    emptyScheduleTitle: { color: theme.text, fontSize: 15, fontWeight: '700' },
    emptyScheduleBody: { color: theme.secondaryText, fontSize: 13, lineHeight: 18, marginTop: 3 },
    councilDemandCard: { padding: 16, borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, backgroundColor: theme.surface, gap: 12 },
    councilDemandIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.accentSoft },
    councilDemandCopy: { gap: 3 },
    councilDemandKicker: { color: theme.accent, fontSize: 11, lineHeight: 15, fontWeight: '700', letterSpacing: 1 },
    councilDemandTitle: { color: theme.text, fontSize: 17, lineHeight: 22, fontWeight: '700' },
    councilDemandBody: { color: theme.secondaryText, fontSize: 13, lineHeight: 19 },
    councilDemandButton: { minHeight: 48, borderRadius: 13, backgroundColor: theme.accentFill, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    councilDemandButtonDone: { backgroundColor: theme.accentSoft },
    councilDemandButtonText: { color: '#FFFFFF', fontSize: 14, lineHeight: 19, fontWeight: '700' },
    sourceLine: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 4 },
    sourceText: { flex: 1, color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, fontWeight: '600' },
    changeNotice: { borderRadius: 14, backgroundColor: `${theme.warning}14`, padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 11, borderWidth: StyleSheet.hairlineWidth, borderColor: `${theme.warning}45` },
    changeIcon: { height: 40, width: 40, borderRadius: 14, backgroundColor: theme.surface, alignItems: 'center', justifyContent: 'center' },
    changeCopy: { flex: 1 },
    changeTitle: { color: theme.text, fontSize: 14.5, fontWeight: '700' },
    changeBody: { color: theme.secondaryText, fontSize: 13, lineHeight: 18, marginTop: 3, fontWeight: '600' },
    changeFoot: { color: theme.secondaryText, fontSize: 12, lineHeight: 17, marginTop: 5 },
    sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
    sectionKicker: { color: theme.secondaryText, fontFamily: appFonts.text, fontSize: 12, letterSpacing: 0.9, fontWeight: '700' },
    sectionTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 24, lineHeight: 29, fontWeight: '700', letterSpacing: -0.65, marginTop: 3 },
    linkButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 3 },
    linkText: { color: theme.accent, fontSize: 13, fontWeight: '800' },
    scheduleList: { backgroundColor: theme.surface, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, overflow: 'hidden' },
    scheduleRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator, gap: 11 },
    dayBlock: { width: 42, alignItems: 'center' },
    dayName: { color: theme.secondaryText, fontSize: 12, fontWeight: '700', letterSpacing: 0.4 },
    dayNumber: { color: theme.text, fontFamily: appFonts.rounded, fontSize: 21, fontWeight: '600', fontVariant: ['tabular-nums'], letterSpacing: -0.4, marginTop: 1 },
    iconDisc: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
    rowCopy: { flex: 1 },
    rowTitle: { color: theme.text, fontSize: 15, fontWeight: '700' },
    rowBody: { color: theme.secondaryText, fontSize: 12.5, fontWeight: '500', marginTop: 2 },
    dot: { height: 8, width: 8, borderRadius: 4 },
    pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
    pickerPage: { flex: 1, backgroundColor: theme.background },
    pickerHeader: { backgroundColor: theme.surface, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    modalKicker: { color: theme.accent, fontSize: 12, letterSpacing: 0.9, fontWeight: '700' },
    modalTitle: { color: theme.text, fontFamily: appFonts.display, fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -0.75, marginTop: 3 },
    modalClose: { height: 44, width: 44, borderRadius: 22, backgroundColor: theme.elevated, alignItems: 'center', justifyContent: 'center' },
    pickerContent: { padding: 18, paddingBottom: 30, gap: 16 },
    pickerList: { backgroundColor: theme.surface, borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.separator, overflow: 'hidden' },
    pickerRow: { minHeight: 82, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.separator },
    pickerRowActive: { backgroundColor: theme.accentSoft },
    pickerIcon: { height: 42, width: 42, borderRadius: 15, backgroundColor: theme.accentSoft, alignItems: 'center', justifyContent: 'center' },
    pickerIconActive: { backgroundColor: theme.accentFill },
    pickerCopy: { flex: 1 },
    pickerTitle: { color: theme.text, fontSize: 15, fontWeight: '700' },
    pickerBody: { color: theme.secondaryText, fontSize: 12.5, lineHeight: 17, marginTop: 3 },
    manageButton: { minHeight: 54, backgroundColor: theme.accentSoft, borderRadius: 16, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 10 },
    manageButtonText: { flex: 1, color: theme.accent, fontSize: 15, fontWeight: '700' },
  });
}

export type TodayStyles = ReturnType<typeof createTodayStyles>;
