import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
  page: { flex: 1 },
  header: { borderBottomWidth: StyleSheet.hairlineWidth },
  headerRow: { height: 58, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  close: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '700' },
  content: { padding: 16, paddingBottom: 42, gap: 24 },
  finder: { gap: 10 },
  categoryTabs: { gap: 8, paddingRight: 6 },
  categoryTab: { minHeight: 44, borderRadius: 22, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center' },
  categoryTabText: { fontSize: 13, fontWeight: '700' },
  hidden: { display: 'none' },
  section: { gap: 9 },
  sectionLabel: { fontSize: 13, fontWeight: '600', paddingHorizontal: 3 },
  card: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 15, overflow: 'hidden' },
  row: { minHeight: 66, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth },
  rowIcon: { width: 40, height: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  rowCopy: { flex: 1 },
  rowTitle: { fontSize: 15, lineHeight: 20, fontWeight: '600' },
  rowDetail: { fontSize: 12.5, lineHeight: 17, marginTop: 3 },
  toggleRow: { minHeight: 66, paddingHorizontal: 14, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  toggleTitle: { fontSize: 14.5, lineHeight: 19, fontWeight: '600' },
  toggleDetail: { fontSize: 12.5, lineHeight: 17, marginTop: 3 },
  segment: { flexDirection: 'row', padding: 3, borderRadius: 11, gap: 2 },
  segmentOption: { flex: 1, minHeight: 42, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  segmentText: { fontSize: 13.5, fontWeight: '600' },
  platformNote: { borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  platformText: { flex: 1, fontSize: 13.5, lineHeight: 19 },
  privacyRow: { padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  privacyText: { flex: 1, fontSize: 13, lineHeight: 19 },
  about: { padding: 16, borderBottomWidth: StyleSheet.hairlineWidth },
  aboutName: { fontSize: 15, fontWeight: '700' },
  aboutDetail: { fontSize: 13, marginTop: 5 },
  pressed: { opacity: 0.65 },
  disabled: { opacity: 0.45 },
});
