import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  page: { flex: 1 },
  safe: { paddingHorizontal: 16, paddingTop: 4 },
  topRow: { height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  topButton: { width: 54, height: 44, justifyContent: 'center' },
  skip: { minWidth: 54, height: 44, alignItems: 'flex-end', justifyContent: 'center' },
  skipText: { fontSize: 15, fontWeight: '600' },
  progressLabel: { fontSize: 13, fontWeight: '600' },
  progressTrack: { height: 4, borderRadius: 2, overflow: 'hidden' },
  progressFill: { height: 4, borderRadius: 2 },
  body: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center' },
  inlineNotice: { paddingHorizontal: 22, paddingTop: 12 },
  step: { flex: 1, paddingHorizontal: 22, paddingTop: 38, paddingBottom: 28, gap: 16 },
  heroIcon: { width: 74, height: 74, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 34, lineHeight: 40, fontWeight: '700', letterSpacing: -1.15 },
  copy: { fontSize: 16, lineHeight: 23 },
  promise: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 15, gap: 14 },
  promiseRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  promiseText: { fontSize: 15, fontWeight: '600' },
  primary: { minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 'auto', paddingHorizontal: 16 },
  primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  postcodeInput: { height: 56, borderRadius: 13, borderWidth: 1, paddingHorizontal: 15, fontSize: 18, fontWeight: '600' },
  addressList: { flex: 1 },
  addressOption: { minHeight: 70, borderWidth: 1, borderRadius: 13, padding: 13, marginBottom: 9, flexDirection: 'row', alignItems: 'center', gap: 10 },
  addressCopy: { flex: 1 },
  addressTitle: { fontSize: 14, lineHeight: 19, fontWeight: '600' },
  addressPostcode: { fontSize: 13, marginTop: 3 },
  coverageCard: { minHeight: 68, borderRadius: 15, padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
  coverageCopy: { flex: 1 },
  coverageTitle: { fontSize: 14, lineHeight: 19, fontWeight: '700' },
  coverageDetail: { flex: 1, fontSize: 13, lineHeight: 18, marginTop: 2 },
  resultCard: { minHeight: 84, borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  resultIcon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  resultDate: { fontSize: 17, lineHeight: 22, fontWeight: '700' },
  resultBin: { fontSize: 14, lineHeight: 19, marginTop: 3 },
  switchCard: { minHeight: 82, borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  switchIcon: { width: 46, height: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  switchCopy: { flex: 1 },
  switchTitle: { fontSize: 16, fontWeight: '700' },
  switchDetail: { fontSize: 14, marginTop: 4 },
  timePicker: { padding: 4, borderRadius: 13, flexDirection: 'row', gap: 3 },
  time: { flex: 1, minHeight: 48, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  timeText: { fontSize: 15, fontWeight: '700' },
  confirmation: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 16 },
  confirmTitle: { fontSize: 16, lineHeight: 22, fontWeight: '700' },
  confirmDetail: { fontSize: 14, lineHeight: 20, marginTop: 5 },
  disabled: { opacity: 0.5 },
});
