import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const distDirectory = path.resolve('dist');
const cacheableExtensions = new Set([
  '.css',
  '.html',
  '.ico',
  '.js',
  '.json',
  '.png',
  '.svg',
  '.webp',
  '.woff',
  '.woff2',
]);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const target = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(target) : [target];
  }));
  return nested.flat();
}

const files = (await walk(distDirectory))
  .filter((file) => cacheableExtensions.has(path.extname(file)))
  .filter((file) => path.basename(file) !== 'sw.js');

const paths = new Set(['/']);
for (const file of files) {
  const relative = path.relative(distDirectory, file).split(path.sep).join('/');
  paths.add(`/${relative}`);
  if (relative.endsWith('.html')) {
    const route = `/${relative.slice(0, -'.html'.length)}`.replace(/\/index$/, '') || '/';
    paths.add(route);
  }
}

const fingerprintHash = createHash('sha256');
for (const file of [...files].sort()) {
  fingerprintHash.update(path.relative(distDirectory, file));
  fingerprintHash.update(await readFile(file));
}
const fingerprint = fingerprintHash.digest('hex').slice(0, 12);
const cacheName = `what-bin-${fingerprint}`;
const precache = JSON.stringify([...paths].sort());

const source = `/* Generated by scripts/generate-pwa.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = 'what-bin-';
const PRECACHE_URLS = ${precache};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(PRECACHE_URLS.map(async (url) => {
      try {
        await cache.add(new Request(url, { cache: 'reload' }));
      } catch {
        // A clean URL can be unavailable on a non-production static server.
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.startsWith('/api/')) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      try {
        const response = await fetch(request);
        if (response.ok) await cache.put(request, response.clone());
        return response;
      } catch {
        return (await cache.match(request))
          || (await cache.match(url.pathname))
          || (await cache.match(url.pathname.replace(/\\/$/, '') + '.html'))
          || (await cache.match('/offline'))
          || (await cache.match('/offline.html'))
          || (await cache.match('/'));
      }
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(request, response.clone());
    }
    return response;
  })());
});

self.addEventListener('push', (event) => {
  const payload = event.data?.json?.() || {};
  const title = typeof payload.title === 'string' ? payload.title : 'Bin reminder';
  const options = {
    body: typeof payload.body === 'string' ? payload.body : 'Your collection is coming up.',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    tag: typeof payload.tag === 'string' ? payload.tag : 'bin-reminder',
    renotify: true,
    data: {
      url: typeof payload.url === 'string' ? payload.url : '/schedule',
    },
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = new URL(event.notification.data?.url || '/schedule', self.location.origin).href;
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    const existing = windows.find((client) => new URL(client.url).origin === self.location.origin);
    if (existing) {
      await existing.navigate(target);
      return existing.focus();
    }
    return self.clients.openWindow(target);
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
`;

await writeFile(path.join(distDirectory, 'sw.js'), source);
console.log(`Generated dist/sw.js with ${paths.size} precached URLs (${cacheName}).`);
