import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import {
  assertPrecacheBudget,
  buildPrecachePaths,
  exportedHtmlRoute,
  privateNavigationPath,
  serviceWorkerCacheSafetySource,
} from './pwa-cache-safety.mjs';
import { serviceWorkerNotificationSafetySource } from './pwa-notification-safety.mjs';

const distDirectory = path.resolve('dist');
const cacheableExtensions = new Set([
  '.css',
  '.html',
  '.ico',
  '.js',
  '.json',
  '.png',
  '.svg',
  '.webp',
  '.woff',
  '.woff2',
]);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async (entry) => {
    const target = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(target) : [target];
  }));
  return nested.flat();
}

const files = (await walk(distDirectory))
  .filter((file) => cacheableExtensions.has(path.extname(file)))
  .filter((file) => path.basename(file) !== 'sw.js')
  .filter((file) => {
    const relative = path.relative(distDirectory, file).split(path.sep).join('/');
    const route = exportedHtmlRoute(relative);
    return !route || !privateNavigationPath(route);
  });

const relativeFiles = files.map((file) => path.relative(distDirectory, file).split(path.sep).join('/'));
const paths = buildPrecachePaths(relativeFiles);

const fingerprintHash = createHash('sha256');
let totalPrecacheBytes = 0;
for (const file of [...files].sort()) {
  const contents = await readFile(file);
  fingerprintHash.update(path.relative(distDirectory, file));
  fingerprintHash.update(contents);
  totalPrecacheBytes += contents.byteLength;
}
assertPrecacheBudget({ urlCount: paths.length, totalBytes: totalPrecacheBytes });
const fingerprint = fingerprintHash.digest('hex').slice(0, 12);
const cacheName = `what-bin-${fingerprint}`;
const precache = JSON.stringify(paths);

const source = `/* Generated by scripts/generate-pwa.mjs. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const RUNTIME_CACHE_NAME = ${JSON.stringify(`${cacheName}-runtime`)};
const PUBLIC_API_CACHE_NAME = ${JSON.stringify(`${cacheName}-public-api`)};
const CACHE_PREFIX = 'what-bin-';
const PRECACHE_URLS = ${precache};

${serviceWorkerNotificationSafetySource()}

${serviceWorkerCacheSafetySource()}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(PRECACHE_URLS.map(async (url) => {
      try {
        await cache.add(new Request(url, { cache: 'reload' }));
      } catch {
        // A clean URL can be unavailable on a non-production static server.
      }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => (
        name.startsWith(CACHE_PREFIX)
        && name !== CACHE_NAME
        && name !== RUNTIME_CACHE_NAME
        && name !== PUBLIC_API_CACHE_NAME
      ))
      .map((name) => caches.delete(name)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    await Promise.all(clients.map((client) => client.postMessage({
      type: 'PWA_ACTIVATED',
      version: CACHE_NAME,
    })));
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname === '/api' || url.pathname.startsWith('/api/')) {
    if (!runtimeCacheablePublicApi(request, url, self.location.origin)) return;
    event.respondWith((async () => {
      const cache = await caches.open(PUBLIC_API_CACHE_NAME);
      try {
        const response = await fetch(request);
        if (publicApiResponseCacheable(response)) {
          await cache.put(request, response.clone());
        } else {
          await cache.delete(request);
        }
        return response;
      } catch (error) {
        const cached = await cache.match(request);
        if (cached) return cached;
        throw error;
      }
    })());
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const precache = await caches.open(CACHE_NAME);
      const cacheableNavigation = runtimeCacheableNavigation(url, self.location.origin);
      let runtimeCache;
      try {
        const response = await fetch(request);
        if (response.ok && cacheableNavigation) {
          runtimeCache = await caches.open(RUNTIME_CACHE_NAME);
          await runtimeCache.put(request, response.clone());
          await trimRuntimeCache(runtimeCache);
        }
        return response;
      } catch {
        if (cacheableNavigation) {
          runtimeCache ??= await caches.open(RUNTIME_CACHE_NAME);
          const cachedNavigation = (await runtimeCache.match(request))
            || (await precache.match(request))
            || (await precache.match(url.pathname))
            || (await precache.match(url.pathname.replace(/\\/$/, '') + '.html'));
          if (cachedNavigation) return cachedNavigation;
        }
        return (await precache.match('/offline'))
          || (await precache.match('/offline.html'))
          || (await precache.match('/'));
      }
    })());
    return;
  }

  if (!runtimeCacheableAsset(url, self.location.origin)) {
    event.respondWith(fetch(request));
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(RUNTIME_CACHE_NAME);
      await cache.put(request, response.clone());
      await trimRuntimeCache(cache);
    }
    return response;
  })());
});

self.addEventListener('push', (event) => {
  let rawPayload = {};
  try {
    rawPayload = event.data?.json?.() || {};
  } catch {
    // Malformed or non-JSON push data falls back to a safe generic reminder.
  }
  const payload = sanitiseNotificationPayload(rawPayload);
  const options = {
    body: payload.body,
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    tag: payload.tag,
    renotify: true,
    data: {
      url: payload.url,
    },
    actions: payload.actions,
  };
  event.waitUntil(self.registration.showNotification(payload.title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const actionTarget = notificationActionTarget(
    event.action,
    event.notification.data?.url,
  );
  if (!actionTarget) return;
  const target = new URL(
    actionTarget,
    self.location.origin,
  ).href;
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    const existing = windows.find((client) => new URL(client.url).origin === self.location.origin);
    if (existing) {
      await existing.navigate(target);
      return existing.focus();
    }
    return self.clients.openWindow(target);
  })());
});

self.addEventListener('message', (event) => {
  const type = event.data?.type;
  const reply = (payload) => {
    if (event.ports?.[0]) event.ports[0].postMessage(payload);
    else event.source?.postMessage?.(payload);
  };
  if (type === 'SKIP_WAITING') {
    event.waitUntil(self.skipWaiting());
    return;
  }
  if (type === 'PWA_CACHE_STATUS') {
    event.waitUntil((async () => {
      const names = (await caches.keys()).filter((name) => name.startsWith(CACHE_PREFIX));
      const entryCounts = await Promise.all(names.map(async (name) => ({
        name,
        entries: (await (await caches.open(name)).keys()).length,
      })));
      reply({ type: 'PWA_CACHE_STATUS', version: CACHE_NAME, caches: entryCounts });
    })());
    return;
  }
  if (type === 'PWA_CLEAR_CACHES') {
    event.waitUntil((async () => {
      const names = (await caches.keys()).filter((name) => name.startsWith(CACHE_PREFIX));
      await Promise.all(names.map((name) => caches.delete(name)));
      reply({ type: 'PWA_CACHE_CLEARED', deletedCaches: names.length });
    })());
  }
});
`;

await writeFile(path.join(distDirectory, 'sw.js'), source);
console.log(`Generated dist/sw.js with ${paths.length} precached URLs and ${totalPrecacheBytes} bytes (${cacheName}).`);
