import { StyleSheet } from 'react-native';

import { appFonts } from '@/lib/design-system';

export const reportsStyles = StyleSheet.create({
  page: { flex: 1 },
  body: { flex: 1, minHeight: 0 },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomLeftRadius: 28, borderBottomRightRadius: 28, overflow: 'hidden' },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  headerCopy: { flex: 1, minWidth: 0 },
  kicker: { fontFamily: appFonts.text, fontSize: 13, fontWeight: '700' },
  title: { fontSize: 34, lineHeight: 40, fontWeight: '700', letterSpacing: -1.1, marginTop: 2 },
  subtitle: { fontSize: 15, lineHeight: 20, marginTop: 2 },
  iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  listPane: { flex: 1, minWidth: 0, borderRightWidth: StyleSheet.hairlineWidth },
  listContent: { padding: 16, paddingBottom: 112 },
  listHeader: { gap: 12, marginBottom: 14 },
  reportCount: { fontSize: 13, lineHeight: 18, fontWeight: '700' },
  itemGap: { height: 10 },
  explainer: { padding: 14, borderRadius: 14, flexDirection: 'row', gap: 11, alignItems: 'flex-start' },
  explainerText: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  rowGroup: { gap: 10 },
  reportRow: { minHeight: 82, borderWidth: StyleSheet.hairlineWidth, borderRadius: 15, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 },
  rowCopy: { flex: 1, minWidth: 0 },
  rowTitle: { fontSize: 16, lineHeight: 21, fontWeight: '700' },
  rowMeta: { fontSize: 13, lineHeight: 18, marginTop: 2 },
  rowStatus: { fontSize: 12, lineHeight: 17, fontWeight: '700', marginTop: 4 },
  compactDetail: { gap: 9 },
  detailHeading: { fontSize: 14, lineHeight: 19, fontWeight: '700', paddingHorizontal: 2 },
  detailPane: { flex: 1 },
  detailContent: { padding: 24, paddingBottom: 112 },
  detailKicker: { fontSize: 13, lineHeight: 18, fontWeight: '700' },
  detailTitle: { fontSize: 29, lineHeight: 35, fontWeight: '700', letterSpacing: -0.7, marginTop: 3 },
  detailSubtitle: { fontSize: 14, lineHeight: 20, marginTop: 5, marginBottom: 18, maxWidth: 620 },
  detailEmpty: { flex: 1, padding: 24 },
  card: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 15, gap: 13 },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  reportIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  cardCopy: { flex: 1 },
  cardTitle: { fontSize: 17, lineHeight: 22, fontWeight: '700' },
  cardMeta: { fontSize: 13, marginTop: 3 },
  status: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 6, maxWidth: 115 },
  statusText: { fontSize: 12, lineHeight: 16, fontWeight: '700', textAlign: 'center' },
  detailGroup: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 10, gap: 7 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  detailLabel: { fontSize: 13 },
  detailValue: { flexShrink: 1, fontSize: 13, fontWeight: '600', textAlign: 'right' },
  referenceRow: { flexDirection: 'row', gap: 8 },
  recollectionGroup: { gap: 7 },
  recollectionLabel: { fontSize: 13, lineHeight: 18, fontWeight: '600' },
  referenceInput: { flex: 1, height: 44, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 11, fontSize: 14 },
  smallButton: { minWidth: 68, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  smallButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  actions: { gap: 9 },
  actionPair: { flexDirection: 'row', gap: 9 },
  pairButton: { flex: 1, minHeight: 46, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  secondaryButton: { minHeight: 46, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  secondaryButtonText: { fontSize: 14, fontWeight: '700' },
  primaryButton: { minHeight: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  cancelButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  cancelText: { fontSize: 14, fontWeight: '700' },
  empty: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, padding: 28, alignItems: 'center' },
  emptyTitle: { fontSize: 18, fontWeight: '700', marginTop: 12 },
  emptyCopy: { fontSize: 14, lineHeight: 20, textAlign: 'center', marginTop: 7, maxWidth: 330 },
  historyLink: { minHeight: 70, borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, paddingHorizontal: 14, marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 11 },
  historyCopy: { flex: 1 },
  historyTitle: { fontSize: 15, fontWeight: '700' },
  historyDetail: { fontSize: 13, marginTop: 3 },
  pressed: { opacity: 0.66 },
});
